# Generated by Django 4.2.6 on 2023-12-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_zone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
